site_name: AI Code Development Platform
site_description: Transform software development through intelligent AI orchestration with human-in-the-loop control
site_author: AI Code Development Platform Team
site_url: https://aicode-dev-platform.com

# Repository information
repo_name: AI Code Platform
repo_url: https://github.com/aicode/dev-platform
edit_uri: edit/main/docs/

# Navigation structure optimized for user adoption and onboarding
nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Quick Start: getting-started/quick-start.md
    - Solo Developers: getting-started/solo-developers.md
    - Development Teams: getting-started/teams.md
    - Enterprise: getting-started/enterprise.md
  - Features:
    - Platform Overview: features/overview.md
    - AI Agent Orchestration: features/ai-orchestration.md
    - Cross-Platform Development: features/cross-platform.md
    - Agile Workflow Automation: features/agile-workflows.md
    - Human-in-the-Loop Controls: features/human-controls.md
    - Code Quality & TDD: features/quality-tdd.md
    - GitHub Integration: features/github-integration.md
  - Use Cases:
    - Mobile App Development: use-cases/mobile-development.md
    - Web Application Development: use-cases/web-development.md
    - Desktop Applications: use-cases/desktop-development.md
    - Team Collaboration: use-cases/team-collaboration.md
    - Enterprise Development: use-cases/enterprise-development.md
  - Pricing & Plans:
    - Subscription Tiers: pricing/tiers.md
    - Feature Comparison: pricing/comparison.md
    - Enterprise Solutions: pricing/enterprise.md
  - Integration Guides:
    - Claude Code Max: integrations/claude-code-max.md
    - Context7 Research: integrations/context7.md
    - GitHub Projects: integrations/github.md
    - CI/CD Pipelines: integrations/cicd.md
    - Third-Party Tools: integrations/third-party.md
  - User Guides:
    - Creating Your First Project: guides/first-project.md
    - Setting Up Development Workflows: guides/workflows.md
    - Managing Team Collaboration: guides/team-management.md
    - Customizing AI Behavior: guides/ai-customization.md
    - Performance Optimization: guides/optimization.md
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - Performance Problems: troubleshooting/performance.md
    - Integration Issues: troubleshooting/integrations.md
    - FAQ: troubleshooting/faq.md
  - Support:
    - Community Resources: support/community.md
    - Documentation Updates: support/updates.md
    - Contact & Support: support/contact.md

# Theme configuration with Material theme
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  
  # Color scheme and branding
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Typography and fonts
  font:
    text: Roboto
    code: Roboto Mono
  
  # Features and navigation
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - toc.follow
    - toc.integrate
  
  # Logo and favicon
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  
  # Custom icons
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Extensions for enhanced functionality
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  
  # PyMdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: aicode
      repo: dev-platform
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins for enhanced functionality
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: aicode/dev-platform
      branch: main

# Additional JavaScript and CSS
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

# Extra configuration for analytics and social
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aicode/dev-platform
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aicode_platform
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/aicode
  
  version:
    provider: mike
    default: stable
  
  generator: false

# Copyright and footer
copyright: |
  &copy; 2024 AI Code Development Platform Team. 
  <a href="#__consent">Change cookie settings</a>