apiVersion: v1
kind: Secret
metadata:
  name: aicode-secrets
  namespace: aicode-staging
type: Opaque
stringData:
  DATABASE_URL: "postgresql://aicode_user:REPLACE_WITH_PASSWORD@postgres-service:5432/aicode_staging"
  JWT_SECRET: "REPLACE_WITH_JWT_SECRET"
  JWT_REFRESH_SECRET: "REPLACE_WITH_JWT_REFRESH_SECRET"
  REDIS_URL: "redis://redis-service:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: aicode-staging
type: Opaque
stringData:
  POSTGRES_USER: "aicode_user"
  POSTGRES_PASSWORD: "REPLACE_WITH_PASSWORD"
  POSTGRES_DB: "aicode_staging"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: aicode-staging
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: # This will be populated by CI/CD pipeline