apiVersion: v1
kind: Service
metadata:
  name: aicode-api
  namespace: aicode-staging
  labels:
    app: aicode-api
    environment: staging
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: aicode-api
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: aicode-staging
  labels:
    app: nginx-proxy
    environment: staging
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nginx-proxy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"